version: '3.10'
services:
    backend_flask_app:
        container_name: ${TEAM_NAME}_backend_app
        restart: always
        build:
                context: ./backend
                dockerfile: Dockerfile
        ports: 
                - 0.0.0.0:${APP_PORT}:5000
        depends_on:
                - db
        environment:
                - DB_NAME=${TEAM_NAME}_db
        networks:
                flask_network:
                        aliases:
                                - flask-network
        command: flask run --host=0.0.0.0 --port=5000
    db:
        container_name: ${TEAM_NAME}_db
        image: mysql:latest
        restart: always
        environment:
                - MYSQL_USER=admin
                - MYSQL_PASSWORD=admin
                - MYSQL_DATABASE=kardashiandb
                - MYSQL_ROOT_PASSWORD=admin
        volumes:
                - flask_volume:/var/lib/mysql
                - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
                - flask_network
volumes:
        flask_volume:
networks:
        flask_network: